### ISSUE TITLE
Encoding errors when using a dictionary using zstdmt

### ISSUE THREAD

**Issue by mestia** [facebook/zstd#944]
Dear zstd team, 
There seem to be a problem with zstd decoding as described in this bug:
[#883816](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883816)
I see the same problem on my system.

```
When using a pre-made dictionary, zstdmt will generate corrupted files:

[guus@haplo]/dev/shm/corpus>zstd --rm -D ../dictionary *
[guus@haplo]/dev/shm/corpus>zstd --rm -D ../dictionary -d *
[guus@haplo]/dev/shm/corpus>zstdmt --rm -D ../dictionary *
[guus@haplo]/dev/shm/corpus>zstdmt --rm -D ../dictionary -d *
ar,S=18008914:2,.zst : Decoding error (36) : Corrupted block detected
ar,S=6386609:2,S.zst : Decoding error (36) : Corrupted block detected
ar,S=6382007:2,S.zst : Decoding error (36) : Corrupted block detected
[...]
[guus@haplo]/dev/shm/corpus>zstd --rm -D ../dictionary -d *.zst
ar,S=18008914:2,.zst : Decoding error (36) : Corrupted block detected
ar,S=6386609:2,S.zst : Decoding error (36) : Corrupted block detected
ar,S=6382007:2,S.zst : Decoding error (36) : Corrupted block detected
[...]

Not all files are corrupt, only 1% has problems.
```
thank you!

**Comment by Cyan4973** [comment]
We would need a reproduction case to investigate.
I tried this test setup using multiple test files, but none of them failed.

**Comment by gsliepen** [comment]
I'd like to, but the files I tried it on is my personal mailbox, so you can imagine that I do not want to share that. I could not reproduce it on maildirs from public mailing lists such as debian-devel. However, I did notice that it is always the largest files that are corrupted. Out of ~1500 files, 1000 of them are between 1 and 10 kilobyte in size, then 400 of them are between 10 and 100 kilobyte in size, and then there's the rest which goes up to 25 megabytes in size. The debian-devel mailing list doesn't have such a distribution, the largest file there is only 90 kilobytes.

**Comment by Cyan4973** [comment]
I've been testing again this setup with an extended test set containing large files (> 10 MB),
but none of them failed so far.
I'm afraid I'll need a reproduction case to be able to investigate.

**Comment by gsliepen** [comment]
I've managed to create a testcase I feel comfortable in sharing, that reproduces the issue 100% of the time on my machine. SInce it's too large to attach to a GitHub issue, I've temporarily made it available here:

http://tinc-vpn.org/temp/zstd-testcase.tar.xz

Note, I get this issue on a CPU with 6 cores, 12 threads.

**Comment by Cyan4973** [comment]
Thanks for the reproduction case.
I could confirm the diagnosis : `v1.3.2` fails on a few files (about a dozen),
while `dev` branch version works just fine for all files.
Therefore, the fix is already integrated, and will be part of next release.

In the meantime, if you urgently need a quick fix, you could select one of these options : 
- switch to the `dev` branch, since the bug is fixed there
- disable multi-threading, since it's only useful for large files (> several MB)
- disable dictionary, since it's only effective for small files (< several KB), while its impact is negligible for large files
- route messages to use either dictionary (when they are small) or multi-threading (when they are large), but not both at the same time.

**Comment by terrelln** [comment]
git bisect with this script says that it is fixed by commit fc8d293460d6767558843ac8231c249dcc704382 from PR #891.

**Comment by mestia** [comment]
Thank you for looking on it and for the test case. As far as I see the fix from commit [fc8d293](https://github.com/facebook/zstd/commit/fc8d293460d6767558843ac8231c249dcc704382) doesn't solve the issue. I still get "Corrupted block detected" messages with the test case provided by  @gsliepen.
Do you have plans for releasing a new version of zstd any time soon ? If not, then I think I'll take a snapshot of the dev branch to update  zstd v1.3.2 in Debian. Or would you advise against that ? Thank you.

**Comment by gsliepen** [comment]
On Thu, Dec 14, 2017 at 06:02:02PM +0000, Yann Collet wrote:

> Closed #944 via e28305fcca441564a57758d84da8ef73afe7d85d.

I can confirm that that fixed the issue. Thanks!

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>
